name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ${{secrets.SSH_KEY_PATH}}
          sudo chmod 600 ${{secrets.SSH_KEY_PATH}}
          ssh-keyscan -H ${{secrets.DEPLOY_SERVER}} > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_KEY: ${{secrets.SSH_KEY}}
          SSH_KEY_PATH: ${{secrets.SSH_KEY_PATH}}
      - run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $1}')" >> $GITHUB_ENV
        shell: bash
      - name: Run Makefile
        env:
          TOKEN: ${{ secrets.TOKEN }}
          BUCKET_NAME: ${{secrets.BUCKET_NAME }}
          ACCESS_KEY_ID: ${{secrets.ACCESS_KEY_ID}}
          SECRET_ACCESS_KEY: ${{secrets.SECRET_ACCESS_KEY}}
          SSH_KEY_PATH: ${{secrets.SSH_KEY_PATH}}
          REGION: ${{secrets.REGION}}
          USERNAME: ${{secrets.USERNAME}}
          PASSWORD: ${{secrets.PASSWORD}}
          HOST: ${{secrets.HOST}}
          PORT: ${{secrets.PORT}}
          DEPLOY_SERVER: ${{secrets.DEPLOY_SERVER}}
          DEPLOY_USER: ${{secrets.DEPLOY_USER}}
          SERVICE_NAME: ${{REPOSITORY_NAME}}
        run: make deploy
